### ISSUE TITLE
bug(Account): Undefined chat appears after clearing storage

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#424]
**Issue:**
If you have an account with a chat on it and you clear your cache and start to make a new account. When you finally get into the new account you will land in a chat with a user named Undefined 

Note that this happens more often with the clearing data in the browser compared to using the Clear Data button we have in Settings 

**Screenshot:**
![image](https://github.com/user-attachments/assets/61767198-058f-4d8c-9073-a7ffc570c722)
<img width="864" alt="Screenshot 2024-08-16 at 2 01 25 PM" src="https://github.com/user-attachments/assets/0c3c6a42-47d7-45f7-927d-da395df55a17">

**Comment by phillsatellite** [comment]
Re-opened Lucas and I were both able to replicate this today.

**Comment by stavares843** [comment]
also happens here

**Comment by tooshel** [comment]
Do we have any leads on this one? I have seen it too and it's always after clearing my cache. I figure it was a routing issue. Like, I was already on "/chats" when I clear my cache, I reload, so now it wants to take me to "/chats" again but since I don't have any friends I don't really have any chats and never would have made my way to that page except to type it in or because it was remembered after going though the signup process.
